spring.application.name=notas-java-8

# Configuración SQLite
spring.datasource.url=jdbc:sqlite:db/notas.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialecto específico para Spring Boot 2 + SQLite
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect

# Opciones de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false